//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseCenterMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendence
    {
        public Attendence()
        {
            this.StudentAttendances = new HashSet<StudentAttendance>();
        }
    
        public long ID { get; set; }
        public Nullable<long> GroupID { get; set; }
        public string ClassName { get; set; }
        public System.DateTime ClassDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Attendence Attendence1 { get; set; }
        public virtual Attendence Attendence2 { get; set; }
        public virtual ICollection<StudentAttendance> StudentAttendances { get; set; }
    }
}
