//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseCenterMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupDays = new HashSet<GroupDay>();
            this.Students = new HashSet<Student>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<GroupDay> GroupDays { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
