//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseCenterMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupDay
    {
        public long ID { get; set; }
        public long GroupID { get; set; }
        public System.DateTime TimeFrom { get; set; }
        public System.DateTime TimeTo { get; set; }
        public string Day { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
