//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseCenterMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CourseCenterEntities : DbContext
    {
        public CourseCenterEntities()
            : base("name=CourseCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Attendance> Attendances { get; set; }
        public DbSet<Group> Groups { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<SysNotification> SysNotifications { get; set; }
        public DbSet<SystemUser> SystemUsers { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<GroupDay> GroupDays { get; set; }
    }
}
