//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseCenterMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentAttendance
    {
        public long ID { get; set; }
        public long StudentID { get; set; }
        public long AttendanceID { get; set; }
        public Nullable<bool> Attend { get; set; }
        public Nullable<System.DateTime> AttendanceTime { get; set; }
        public bool HomeWork { get; set; }
        public bool Sheet { get; set; }
        public bool AdditionalHomeWork { get; set; }
        public decimal SheetMarks { get; set; }
        public string SheetNotes { get; set; }
        public string Note { get; set; }
    
        public virtual Attendence Attendence { get; set; }
        public virtual Student Student { get; set; }
    }
}
