//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseCenterMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long ID { get; set; }
        public long StudentID { get; set; }
        public int Type { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Value { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
